name: spa_server
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  path: ^1.7.0
  shelf_router: ^0.7.4
  shelf_static: ^0.2.9+1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
