name: spa_server
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  shelf_router: ^1.1.1
  shelf_static: ^1.1.0
  crypto: ^3.0.1
  mongo_dart: ^0.7.2
  dart_jsonwebtoken: ^2.3.2
  envify: ^2.0.2
  redis: ^2.0.0
  uuid: ^3.0.5

dev_dependencies:
  http: ^0.13.4
  lints: ^1.0.1
  test: ^1.14.4
  envify_generator: ^2.0.2
  build_runner: ^2.1.4
